# @package hydra.job_logging

version: 1
formatters:
  default:
    format: "[%(asctime)s | %(name)s | %(levelname)s]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: pytorch_yard.utils.logging.RichConsoleHandler
    formatter: default
  file:
    class: pytorch_yard.utils.logging.RichFileHandler
    formatter: default
    # relative to the job log directory
    filename: ${hydra.job.name}.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false